
VERSION = "v1.2.1"
YEAR = "2020 - 2025"

PLACEHOLDER_VERSION = "%v%"
PLACEHOLDER_YEAR = "%year%"

EUR_ENCODING = "ISO-8859-15"
RUS_ENCODING = "CP1251"

ICON_PATH = "assets/EESicon.ico"
LOGO_PATH = "assets/EESicon.png"
