# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/bene/Windows_Daten/Programmierung_Modding/Empire Earth/GitHub/Empire-Earth-Studio-2/src/lib/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 708)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabs.setSizeIncrement(QtCore.QSize(0, 0))
        self.MainTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.MainTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainTabs.setElideMode(QtCore.Qt.ElideNone)
        self.MainTabs.setUsesScrollButtons(True)
        self.MainTabs.setTabsClosable(False)
        self.MainTabs.setMovable(True)
        self.MainTabs.setObjectName("MainTabs")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_description = QtWidgets.QLabel(self.tab_main)
        self.main_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_description.setObjectName("main_description")
        self.verticalLayout_3.addWidget(self.main_description)
        self.MainTabs.addTab(self.tab_main, "")
        self.tab_ssa = QtWidgets.QWidget()
        self.tab_ssa.setObjectName("tab_ssa")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_ssa)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_ssa_label = QtWidgets.QLabel(self.tab_ssa)
        self.tab_ssa_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tab_ssa_label.setObjectName("tab_ssa_label")
        self.verticalLayout.addWidget(self.tab_ssa_label)
        self.tab_ssa_list = QtWidgets.QListWidget(self.tab_ssa)
        self.tab_ssa_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_ssa_list.setAcceptDrops(True)
        self.tab_ssa_list.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tab_ssa_list.setObjectName("tab_ssa_list")
        item = QtWidgets.QListWidgetItem()
        self.tab_ssa_list.addItem(item)
        self.verticalLayout.addWidget(self.tab_ssa_list)
        self.tab_ssa_label_clear = QtWidgets.QPushButton(self.tab_ssa)
        self.tab_ssa_label_clear.setMaximumSize(QtCore.QSize(75, 20))
        self.tab_ssa_label_clear.setStyleSheet("color: rgb(255, 0, 0);")
        self.tab_ssa_label_clear.setObjectName("tab_ssa_label_clear")
        self.verticalLayout.addWidget(self.tab_ssa_label_clear)
        self.widget = QtWidgets.QWidget(self.tab_ssa)
        self.widget.setMinimumSize(QtCore.QSize(0, 43))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab_ssa_label_in = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ssa_label_in.sizePolicy().hasHeightForWidth())
        self.tab_ssa_label_in.setSizePolicy(sizePolicy)
        self.tab_ssa_label_in.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_ssa_label_in.setText("")
        self.tab_ssa_label_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tab_ssa_label_in.setWordWrap(True)
        self.tab_ssa_label_in.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.tab_ssa_label_in.setObjectName("tab_ssa_label_in")
        self.gridLayout_2.addWidget(self.tab_ssa_label_in, 0, 1, 1, 1)
        self.tab_ssa_select_in = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ssa_select_in.sizePolicy().hasHeightForWidth())
        self.tab_ssa_select_in.setSizePolicy(sizePolicy)
        self.tab_ssa_select_in.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_ssa_select_in.setMaximumSize(QtCore.QSize(150, 30))
        self.tab_ssa_select_in.setObjectName("tab_ssa_select_in")
        self.gridLayout_2.addWidget(self.tab_ssa_select_in, 0, 0, 1, 1)
        self.tab_ssa_select_out = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ssa_select_out.sizePolicy().hasHeightForWidth())
        self.tab_ssa_select_out.setSizePolicy(sizePolicy)
        self.tab_ssa_select_out.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_ssa_select_out.setMaximumSize(QtCore.QSize(150, 30))
        self.tab_ssa_select_out.setObjectName("tab_ssa_select_out")
        self.gridLayout_2.addWidget(self.tab_ssa_select_out, 1, 0, 1, 1)
        self.tab_ssa_label_out = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_ssa_label_out.sizePolicy().hasHeightForWidth())
        self.tab_ssa_label_out.setSizePolicy(sizePolicy)
        self.tab_ssa_label_out.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_ssa_label_out.setText("")
        self.tab_ssa_label_out.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tab_ssa_label_out.setWordWrap(True)
        self.tab_ssa_label_out.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.tab_ssa_label_out.setObjectName("tab_ssa_label_out")
        self.gridLayout_2.addWidget(self.tab_ssa_label_out, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.tab_ssa_decompress = QtWidgets.QCheckBox(self.widget)
        self.tab_ssa_decompress.setChecked(True)
        self.tab_ssa_decompress.setTristate(False)
        self.tab_ssa_decompress.setObjectName("tab_ssa_decompress")
        self.verticalLayout_4.addWidget(self.tab_ssa_decompress)
        self.tab_ssa_unpack = QtWidgets.QPushButton(self.widget)
        self.tab_ssa_unpack.setEnabled(False)
        self.tab_ssa_unpack.setCheckable(False)
        self.tab_ssa_unpack.setChecked(False)
        self.tab_ssa_unpack.setDefault(False)
        self.tab_ssa_unpack.setFlat(False)
        self.tab_ssa_unpack.setObjectName("tab_ssa_unpack")
        self.verticalLayout_4.addWidget(self.tab_ssa_unpack)
        self.verticalLayout.addWidget(self.widget)
        self.MainTabs.addTab(self.tab_ssa, "")
        self.tab_sst = QtWidgets.QWidget()
        self.tab_sst.setAcceptDrops(True)
        self.tab_sst.setObjectName("tab_sst")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_sst)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = CDropLabel(self.tab_sst)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("border-color: rgb(197, 197, 197);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px dashed;\n"
"border-radius: 10;\n"
"")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.tab_sst)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_sst)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_sst)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_sst)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_sst)
        self.pushButton_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_sst)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_sst)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_sst)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_sst)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_sst)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_sst)
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_sst)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_sst)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.tab_sst)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_sst)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_sst)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.MainTabs.addTab(self.tab_sst, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout.addWidget(self.checkBox_6)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.MainTabs.addTab(self.tab, "")
        self.tab_cem = QtWidgets.QWidget()
        self.tab_cem.setObjectName("tab_cem")
        self.MainTabs.addTab(self.tab_cem, "")
        self.verticalLayout_2.addWidget(self.MainTabs)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_Studio_II = QtWidgets.QAction(MainWindow)
        self.actionAbout_Studio_II.setObjectName("actionAbout_Studio_II")
        self.actionHelp_from_GitHUb = QtWidgets.QAction(MainWindow)
        self.actionHelp_from_GitHUb.setObjectName("actionHelp_from_GitHUb")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReport_Issue = QtWidgets.QAction(MainWindow)
        self.actionReport_Issue.setObjectName("actionReport_Issue")
        self.menuAbout.addAction(self.actionHelp_from_GitHUb)
        self.menuAbout.addAction(self.actionReport_Issue)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_Studio_II)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.MainTabs.setCurrentIndex(1)
        self.tab_ssa_label_clear.clicked.connect(self.tab_ssa_list.clear)
        self.tab_ssa_label_clear.clicked.connect(self.tab_ssa_label_out.clear)
        self.tab_ssa_label_clear.clicked.connect(self.tab_ssa_label_in.clear)
        self.tab_ssa_label_clear.clicked['bool'].connect(self.tab_ssa_unpack.setEnabled)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Empire Earth Studio II"))
        self.MainTabs.setAccessibleName(_translate("MainWindow", "some random name"))
        self.MainTabs.setAccessibleDescription(_translate("MainWindow", "some random description"))
        self.main_description.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline;\">SOME FUCKING RANDOM TEXT</span></p><p>oiahsdikujashd lkjash dlkajshdlakjshd lkasjhdlkasjh dlaskjdh alskjdh </p><p>aslkjdh aslkhd jalkshd lajksh dlkash dlkash dlkash dlkajsh dalksjh</p><p>dlaksh dlkashlkjdghsgkjdfshgre</p><p><br/></p><p><span style=\" font-weight:600;\">FOLLOW OUR FUCKING DISCORD OK!!?!??!!</span></p></body></html>"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_main), _translate("MainWindow", "Main"))
        self.tab_ssa_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">file list: </span></p></body></html>"))
        __sortingEnabled = self.tab_ssa_list.isSortingEnabled()
        self.tab_ssa_list.setSortingEnabled(False)
        item = self.tab_ssa_list.item(0)
        item.setText(_translate("MainWindow", " just a test"))
        self.tab_ssa_list.setSortingEnabled(__sortingEnabled)
        self.tab_ssa_label_clear.setText(_translate("MainWindow", "clear"))
        self.tab_ssa_select_in.setText(_translate("MainWindow", "Select SSA"))
        self.tab_ssa_select_out.setText(_translate("MainWindow", "Select Output folder"))
        self.tab_ssa_decompress.setText(_translate("MainWindow", "decompress"))
        self.tab_ssa_unpack.setText(_translate("MainWindow", "UNPACK"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_ssa), _translate("MainWindow", "Archives (SSA)"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">DRAG &amp; DROP HERE!!</span></p><p align=\"center\"><br/>You can drop TGA, SST and folders!</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "options:"))
        self.checkBox_4.setText(_translate("MainWindow", "view only"))
        self.checkBox_2.setText(_translate("MainWindow", "autoconvert on Drop"))
        self.checkBox_3.setText(_translate("MainWindow", "overwrite output"))
        self.pushButton_6.setText(_translate("MainWindow", "Bulk convert Folder"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox_7.setText(_translate("MainWindow", "use input folder as output"))
        self.pushButton_5.setText(_translate("MainWindow", "Select File"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_12.setText(_translate("MainWindow", "Output Folder"))
        self.radioButton.setText(_translate("MainWindow", "SST -> TGA"))
        self.radioButton_2.setText(_translate("MainWindow", "TGA -> SST"))
        self.pushButton_7.setText(_translate("MainWindow", "CONVERT"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_sst), _translate("MainWindow", "Textures (SST)"))
        self.label_9.setText(_translate("MainWindow", "options:"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "Select SST file"))
        self.pushButton_10.setText(_translate("MainWindow", "SLICE THAT BABY"))
        self.pushButton_11.setText(_translate("MainWindow", "JOIN"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab), _translate("MainWindow", "Slicer (SST)"))
        self.MainTabs.setTabText(self.MainTabs.indexOf(self.tab_cem), _translate("MainWindow", "3D Models (CEM)"))
        self.label_8.setText(_translate("MainWindow", "Empire Earth Studio II - EE-modders - v0.1"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout_Studio_II.setText(_translate("MainWindow", "About EEStudio II"))
        self.actionHelp_from_GitHUb.setText(_translate("MainWindow", "Help from GitHub"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionReport_Issue.setText(_translate("MainWindow", "Report Issue"))
from .customwidgets import CDropLabel
