ui:
	pyuic5 ui/mainWindow.ui > Ui_mainWindow.py
	pyuic5 ui/aboutWindow.ui > Ui_aboutWindow.py
	pyuic5 ui/progressWindow.ui > Ui_progressWindow.py
	pyuic5 ui/viewerWindow.ui > Ui_viewerWindow.py

.PHONY: ui
